apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Chart.Name }}-worker
  name: {{ .Chart.Name }}-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Chart.Name }}-worker
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      creationTimestamp: null
      labels:
        io.kompose.service: {{ .Chart.Name }}-worker
    spec:
      volumes:
        - hostPath:
            path: '/private/var/www/rebuy'
          name: {{ .Chart.Name }}-hostpath0
      containers:
        - name: octane
          image: {{ .Chart.Name }}
          imagePullPolicy: IfNotPresent
          args: ["php", "artisan", "queue:work"]
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-configmap
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 200m
              memory: 200Mi
          volumeMounts:
            - mountPath: /var/www
              name: {{ .Chart.Name }}-hostpath0
          workingDir: /var/www
      restartPolicy: Always
status: {}