apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  ports:
    - name: "roadrunner"
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: {{ .Chart.Name }}
status:
  loadBalancer: {}
